resources:
- statefulset.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: keycloak-env
  literals:
    - KEYCLOAK_ADMIN=root
    - KEYCLOAK_ADMIN_PASSWORD=passwd
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    - OTEL_SERVICE_NAME=keycloak

