---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  serviceName: "keycloak"
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.0
          imagePullPolicy: IfNotPresent
          args:
            - 'start'
            - '--import-realm'
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: keycloak-env
          volumeMounts:
            - name: apphost-keycloak-data
              mountPath: /opt/keycloak/data
  volumeClaimTemplates:
    - metadata:
        name: apphost-keycloak-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
