---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apitasks
  labels:
    app: apitasks
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: apitasks
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: apitasks
    spec:
      containers:
      - name: apitasks
        image: apitasks:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: apitasks-env
        - secretRef:
            name: apitasks-secrets
      terminationGracePeriodSeconds: 180